return{}
-- return {
--   "Isrothy/neominimap.nvim",
--   version = "v3.x.x",
--   event = "VeryLazy",
--
--   keys = {
--     { "<leader>nm", "<cmd>Neominimap Toggle<cr>", desc = "Toggle Minimap" },
--   },
--
--   opts = {
--     auto_enable = false,
--   },
-- }
